apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRole
metadata:
  labels:
    {{- include "kafkaobjects-operator.labels" . | nindent 4 }}
    {{- with .Values.operator.labels }}
    {{- toYaml . | nindent 4 }}
    {{- end }}
  name: {{ include "kafkaobjects-operator.fullname" . }}
rules:
- apiGroups:
  - xo.ninetypercent.io
  resources:
  - kafkaschemas
  verbs:
  - create
  - delete
  - get
  - list
  - patch
  - update
  - watch
- apiGroups:
  - xo.ninetypercent.io
  resources:
  - kafkaschemas/finalizers
  verbs:
  - update
- apiGroups:
  - xo.ninetypercent.io
  resources:
  - kafkaschemas/status
  verbs:
  - get
  - patch
  - update
- apiGroups:
  - xo.ninetypercent.io
  resources:
  - kafkatopics
  verbs:
  - create
  - delete
  - get
  - list
  - patch
  - update
  - watch
- apiGroups:
  - xo.ninetypercent.io
  resources:
  - kafkatopics/finalizers
  verbs:
  - update
- apiGroups:
  - xo.ninetypercent.io
  resources:
  - kafkatopics/status
  verbs:
  - get
  - patch
  - update