{{- $sm := .Values.serviceMonitor }}
{{- if or $sm.create -}}
apiVersion: monitoring.coreos.com/v1
kind: ServiceMonitor
metadata:
  labels:
    {{- include "kafkaobjects-operator.labels" . | nindent 4 }}
    app: {{ include "kafkaobjects-operator.fullname" . }}
    app.kubernetes.io/component: kafkaobjects-operator
    {{- with $sm.labels }}
    {{- toYaml . | nindent 4 }}
    {{- end }}
  name: {{ include "kafkaobjects-operator.fullname" . }}
  namespace: {{ .Release.Namespace }}
spec:
  endpoints:
  - path: /metrics
    targetPort: 8080
  jobLabel: {{ include "kafkaobjects-operator.fullname" . }}
  namespaceSelector:
    matchNames:
    - {{ .Release.Namespace }}
  selector:
    matchLabels:
      app: {{ include "kafkaobjects-operator.fullname" . }}
{{- end }}