# permissions for end users to edit kafkatopics.
apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRole
metadata:
  labels:
    app.kubernetes.io/name: clusterrole
    app.kubernetes.io/instance: kafkatopic-editor-role
    app.kubernetes.io/component: rbac
    app.kubernetes.io/created-by: kafkaobjects-operator-v2
    app.kubernetes.io/part-of: kafkaobjects-operator-v2
    app.kubernetes.io/managed-by: kustomize
  name: kafkatopic-editor-role
rules:
- apiGroups:
  - xo.90poe.io
  resources:
  - kafkatopics
  verbs:
  - create
  - delete
  - get
  - list
  - patch
  - update
  - watch
- apiGroups:
  - xo.90poe.io
  resources:
  - kafkatopics/status
  verbs:
  - get
