# permissions for end users to view kafkatopics.
apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRole
metadata:
  labels:
    app.kubernetes.io/name: clusterrole
    app.kubernetes.io/instance: kafkatopic-viewer-role
    app.kubernetes.io/component: rbac
    app.kubernetes.io/created-by: kafkaobjects-operator
    app.kubernetes.io/part-of: kafkaobjects-operator
    app.kubernetes.io/managed-by: kustomize
  name: kafkatopic-viewer-role
rules:
- apiGroups:
  - xo.ninetypercent.io
  resources:
  - kafkatopics
  verbs:
  - get
  - list
  - watch
- apiGroups:
  - xo.ninetypercent.io
  resources:
  - kafkatopics/status
  verbs:
  - get
